name: .NET Core CI

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
      
      - name: Restore dependencies
        run: dotnet restore <путь_к_вашему_проекту>

      - name: Build
        run: dotnet build <путь_проекту> --configuration Release --no-restore #дорабатываю

      - name: Test
        run: dotnet test <путь_проекту> --no-restore --verbosity normal  #дорабатываю

      - name: Publish
        run: dotnet publish <путь_проекту> --configuration Release --output ./output #дорабатываю

      - name: Build Docker Image
        run: docker build . -t <работа со сертификатом>:latest #дорабатываю
